version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run: echo build step
      - run: exit 4
  test:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - run: echo test step

workflows:
  version: 2
  build-and-test:
    - build
    - test:
      requires:
        - build
